### ISSUE TITLE
Uncatchable throws

### ISSUE THREAD

**Issue by TanukiSharp** [williamkapke/mongo-mock#116]
Using version `3.8.1` of `mongo-mock`, and in some circumstances, when a function throws, it is uncatchable. Hereafter is a repro, in which I actually added 2 tests because I think they are kind of related.

**package.json**
```json
{
  "name": "mongo-mock-async-issue-repro",
  "main": "index.js",
  "dependencies": {
    "mongo-mock": "^3.8.1"
  }
}
```

**index.js**
```js
const mongodb = require('mongo-mock');

const testHangingCallback = (client) => {
    client.db('myDb').collection('myCollection').insertOne(
        { _id: 1 },
        (error) => {
            if (error) {
                console.log('error:', error);
                return;
            }
            console.log('OK, then what ?');
        }
    );
};

const testHangingAsync = async (client) => {
    await client.db('myDb').collection('myCollection').insertOne({ _id: 1 });
    console.log('OK, then what ?');
};

const testUncatchableThrow = async (client) => {
    try {
        console.log('Try to catch');

        await client.db('myDb').collection('myCollection').findOneAndUpdate({ _id: 1});

        console.log('FAILURE');
    } catch (error) {
        console.log('Nice catch!');
    }
};

const main = async () => {
    mongodb.max_delay = 1;

    const client = await mongodb.MongoClient.connect(
        'mongodb://somewhere/someDb',
        { useNewUrlParser: true }
    );

    // testHangingCallback(client);
    // await testHangingAsync(client);
    // await testUncatchableThrow(client);
};

main();
```

Then, uncomment either `testHangingCallback`, `testHangingAsync` or `testUncatchableThrow` and run it.

### Expected result:

```
OK, then what ?
<end-of-program>
```

### Actual result
```
OK, then what ?
```
The program hangs forever, like a timer is started and never stopped, locking the event loop.

### Expected result
```
Try to catch
Nice catch!
```

Worst case scenario, a big bug let this work, I'm expecting:
```
Try to catch
FAILURE
```

### Actual result

```
Try to catch
<my-path>/mongo-mock-async-issue-repro/node_modules/modifyjs/dist/bundle.js:168
  if (!isPlainObject(mod)) throw ModifyJsError("Modifier must be an object");
                           ^

ModifyJsError: Modifier must be an object
    at ModifyJsError (<my-path>/mongo-mock-async-issue-repro/node_modules/modifyjs/dist/bundle.js:141:11)
    at _modify (<my-path>/mongo-mock-async-issue-repro/node_modules/modifyjs/dist/bundle.js:168:34)
    at modify (<my-path>/mongo-mock-async-issue-repro/node_modules/modifyjs/dist/bundle.js:163:10)
    at modify (<my-path>/mongo-mock-async-issue-repro/node_modules/mongo-mock/lib/collection.js:495:17)
    at Timeout._onTimeout (<my-path>/mongo-mock-async-issue-repro/node_modules/mongo-mock/lib/collection.js:467:26)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by TanukiSharp** [comment]
I cannot reproduce the real problem I wanted to report, but the tests described in the previous post are very related.

Another test you can run to see:
```js
const anotherTest = (client) => {
    client.db('myDb').collection('myCollection').findOneAndUpdate(
        { _id: 1 },
        { name: 'alice' },
        { upsert: true },
        (error) => {
            console.log('ERROR1:', error);
            client.db('myDb').collection('myCollection').findOneAndUpdate(
                { _id: 1, name: 'bob' },
                { name: 'bob' },
                { upsert: true },
                (error) => {
                    console.log('ERROR2:', error);
                }
            );
        }
    );
};
```

Here is the console out:
```
ERROR1: null
ERROR2: { MongoError: E11000 duplicate key error index: myDb.myCollection.$_id_
    at indexError (<my-path>/mongo-mock-async-issue-repro/node_modules/mongo-mock/lib/db.js:277:13)
    at CollectionState.findConflict (<my-path>/mongo-mock-async-issue-repro/node_modules/mongo-mock/lib/db.js:245:18)
    at Timeout._onTimeout (<my-path>/mongo-mock-async-issue-repro/node_modules/mongo-mock/lib/collection.js:452:32)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  name: 'MongoError',
  ok: 1,
  n: 1,
  code: 11000,
  errmsg: 'E11000 duplicate key error index: myDb.myCollection.$_id_',
  writeErrors:
   [ { index: 0,
       code: 11000,
       errmsg: 'E11000 duplicate key error index: myDb.myCollection.$_id_' } ] }
```
And the program hangs forever.

The async version:

```js
const anotherTestAsync = async (client) => {
    console.log('Before');

    await client.db('myDb').collection('myCollection').findOneAndUpdate(
        { _id: 1 },
        { name: 'alice' },
        { upsert: true }
    );

    console.log('Intermediate');

    await client.db('myDb').collection('myCollection').findOneAndUpdate(
        { _id: 1, name: 'bob' },
        { name: 'bob' },
        { upsert: true }
    );

    console.log('After');
};
```

The output is as follow:
```
Before
Intermediate
```
And the program hangs.

In another circumstance I can't really reproduce, the second await was throwing an exception instead of hanging, with the same message as:

```
    ...
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by TanukiSharp** [comment]
Any news ? @williamkapke

**Comment by davidjytang** [comment]
I also encountered `E11000 duplicate key error index` error when making a new MongoClient after closing a old MongoClient using the same connection string.

Once I change the port number in the connection string, the duplicate key error disappears.
